version: '3'

volumes:
  postgres_data: {}
  storage_data: {}
  broker_data: {}

services:
  postgres:
    image: postgres:9.6
    container_name: openroad_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: src/.env

  broker:
    image: redis:5.0.4
    volumes:
      - broker_data:/data
    container_name: redis_broker

  openroad:
    build:
      context: .
      dockerfile: ./deployment/web/Dockerfile
    container_name: openroad
    volumes:
      - storage_data:/src/media
    depends_on:
      - postgres
    env_file: src/.env
    ports:
      - "8000:8000"
    links:
      - postgres

  celery:
    build:
      context: .
      dockerfile: ./deployment/celery/Dockerfile
    container_name: celery
    depends_on:
      - postgres
      - broker
      - openroad
    env_file: src/.env
    links:
    - postgres